"""Trading Exchanges Package - Unified Exchange Interface"""

from trading_agent.exchanges.ccxt_adapter import (
    CCXTAdapter,
    MultiExchangeManager,
    ExchangeConfig,
    RateLimitManager,
    get_default_exchange_configs,
    create_multi_exchange_manager,
)
from trading_agent.exchanges.alpaca_adapter import (
    AlpacaAdapter,
    AlpacaConfig,
    create_alpaca_adapter,
)
from trading_agent.exchanges.oanda_adapter import (
    OANDAAdapter,
    OANDAConfig,
    create_oanda_adapter,
)
from trading_agent.exchanges.order_router import (
    OrderRouter,
    RoutingStrategy,
    BestPriceRouter,
    ExecutionPlan,
    VenueQuote,
)
from trading_agent.exchanges.websocket_manager import (
    WebSocketManager,
    StreamProvider,
    MockStreamProvider,
    WSChannel,
    WSMessage,
    WSMessageType,
    create_mock_manager,
)
from trading_agent.exchanges.health_monitor import (
    HealthMonitor,
    ExchangeHealth,
    HealthStatus,
    Checker,
    DEFAULT_LATENCY_GOOD,
    DEFAULT_LATENCY_DEGRADED,
    DEFAULT_ERROR_RATE_MAX,
    DEFAULT_FAILURES_TO_DOWN,
)
from trading_agent.exchanges.models import (
    Symbol,
    AssetClass,
    MarketType,
    OrderSide,
    OrderType,
    OrderStatus,
    TimeInForce,
    Order,
    Position,
    Balance,
    Ticker,
    OrderBook,
    OrderBookLevel,
    Trade,
    Candle,
    AccountBalance,
    crypto_symbol,
    stock_symbol,
    forex_symbol,
    futures_symbol,
    option_symbol,
    COMMON_CRYPTO,
    COMMON_STOCKS,
    COMMON_FOREX,
)

__all__ = [
    # CCXT
    "CCXTAdapter",
    "MultiExchangeManager",
    "ExchangeConfig",
    "RateLimitManager",
    "get_default_exchange_configs",
    "create_multi_exchange_manager",
    # Alpaca (US Stocks)
    "AlpacaAdapter",
    "AlpacaConfig",
    "create_alpaca_adapter",
    # OANDA (Forex)
    "OANDAAdapter",
    "OANDAConfig",
    "create_oanda_adapter",
    # Order Router
    "OrderRouter",
    "RoutingStrategy",
    "BestPriceRouter",
    "ExecutionPlan",
    "VenueQuote",
    # WebSocket Manager
    "WebSocketManager",
    "StreamProvider",
    "MockStreamProvider",
    "WSChannel",
    "WSMessage",
    "WSMessageType",
    "create_mock_manager",
    # Health Monitor
    "HealthMonitor",
    "ExchangeHealth",
    "HealthStatus",
    "Checker",
    "DEFAULT_LATENCY_GOOD",
    "DEFAULT_LATENCY_DEGRADED",
    "DEFAULT_ERROR_RATE_MAX",
    "DEFAULT_FAILURES_TO_DOWN",
    # Models
    "Symbol",
    "AssetClass",
    "MarketType",
    "OrderSide",
    "OrderType",
    "OrderStatus",
    "TimeInForce",
    "Order",
    "Position",
    "Balance",
    "Ticker",
    "OrderBook",
    "OrderBookLevel",
    "Trade",
    "Candle",
    "AccountBalance",
    "crypto_symbol",
    "stock_symbol",
    "forex_symbol",
    "futures_symbol",
    "option_symbol",
    "COMMON_CRYPTO",
    "COMMON_STOCKS",
    "COMMON_FOREX",
]
