"""Milestone D DoD tests — PortfolioBacktestEngine.

Invariant under test: backtest swaps ONLY broker+clock; the whole decision
authority chain (resolver → StrategyRuntime → StrategyOutput → batch
PortfolioAllocator → PortfolioTargetVector → risk/planner/preflight) is the
live pipeline.

Covers the Definition of Done checklist:
- N=1 parity (hand-recomputed ledger math, exact fill price/time, no lookahead)
- N>1 shared capital pool (gross/symbol caps enforced across symbols)
- permutation/determinism (binding order cannot change results)
- replay produces identical results
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path

import polars as pl
import pytest

from tests.test_multi_pair_runtime import (
    _build_engine,
    _instrument_rules,
    _make_artifact,
)
from trading_agent.authority.config import AuthorityConfig, Environment
from trading_agent.backtest.portfolio_backtest import PortfolioBacktestEngine
from trading_agent.research.promotion import ResearchStage

TF_SEC = 3600


# ── deterministic data ───────────────────────────────────────────────────


def _trend_df(
    base: float,
    *,
    n_flat: int = 45,
    n_trend: int = 34,
    growth: float = 1.008,
    start: datetime | None = None,
) -> pl.DataFrame:
    """Flat warmup then steady uptrend → exactly one MA10/30 bullish cross."""
    start = start or datetime(2024, 1, 1, tzinfo=UTC)
    prices = [base] * n_flat
    p = base
    for _ in range(n_trend):
        p *= growth
        prices.append(p)
    stamps = [start + timedelta(hours=i) for i in range(len(prices))]
    return pl.DataFrame(
        {
            "timestamp": stamps,
            "open": prices,
            "high": [x * 1.001 for x in prices],
            "low": [x * 0.999 for x in prices],
            "close": prices,
            "volume": [1000.0] * len(prices),
        }
    )


def _first_cross_index(df: pl.DataFrame, fast: int = 10, slow: int = 30) -> int:
    closes = df["close"].to_list()
    def ma(i: int, w: int) -> float:
        return sum(closes[i - w + 1 : i + 1]) / w
    for i in range(slow - 1, len(closes)):
        f_now, s_now = ma(i, fast), ma(i, slow)
        f_prev, s_prev = ma(i - 1, fast), ma(i - 1, slow)
        if f_prev <= s_prev and f_now > s_now:
            return i
    raise AssertionError("no bullish cross generated by fixture data")


# ── fixtures ─────────────────────────────────────────────────────────────


@pytest.fixture
def temp_dir():
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        yield Path(d)


@pytest.fixture
def stores(temp_dir):
    from trading_agent.authority.promotion_store import PromotionStateStore
    from trading_agent.research.artifact import PersistentArtifactStore

    promotion_store = PromotionStateStore(temp_dir / "promotion.db")
    artifact_store = PersistentArtifactStore(temp_dir / "artifacts")
    return promotion_store, artifact_store


@pytest.fixture
def config() -> AuthorityConfig:
    cfg = AuthorityConfig.for_environment(Environment.PAPER)
    cfg.exposure.max_portfolio_exposure = 0.95
    cfg.exposure.max_single_symbol_exposure = 0.95
    cfg.exposure.max_single_strategy_exposure = 0.95
    return cfg


def _promote(store_artifact, promotion_store, artifact) -> None:
    from trading_agent.authority.promotion_store import PromotionRecord
    from trading_agent.research.promotion import ResearchPromotionEvent

    event = ResearchPromotionEvent(
        subject_artifact_id=artifact.artifact_id,
        from_stage=ResearchStage.RESEARCH_VALIDATED,
        to_stage=ResearchStage.PAPER_ELIGIBLE,
        evidence_ids=("wfo",),
        actor="pbt-test",
        timestamp=datetime.now(UTC),
    )
    promotion_store.upsert(
        PromotionRecord(
            artifact_id=artifact.artifact_id,
            stage=ResearchStage.PAPER_ELIGIBLE,
            latest_event=event,
            updated_at=datetime.now(UTC),
        )
    )


def _make_engine(config, stores, temp_dir, rules):
    eng = _build_engine(config, stores, temp_dir, rules)
    yield eng
    eng._graceful_shutdown()


def _run_btc_only(config, stores, temp_dir, **kw):
    rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
    eng = _build_engine(config, stores, temp_dir, rules)
    try:
        _, artifact_store = stores
        promotion_store = stores[0]
        art = _make_artifact(
            artifact_store,
            promotion_store,
            symbol="BTC/USDT",
            timeframe="1h",
            fast=10,
            slow=30,
        )
        _promote(None, promotion_store, art)
        bars = {("BTC/USDT", "1h"): _trend_df(60_000.0)}
        pbt = PortfolioBacktestEngine(
            eng,
            bars=bars,
            initial_cash=kw.pop("initial_cash", 100_000.0),
            **kw,
        )
        return pbt.run("paper"), eng, art
    finally:
        pass


# ── DoD: PortfolioBacktestEngine exists + N=1 parity ─────────────────────


class TestN1Parity:
    def test_single_binding_full_ledger_math_and_no_lookahead(
        self, config, stores, temp_dir
    ):
        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            art = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="BTC/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            _promote(None, promotion_store, art)

            df = _trend_df(60_000.0)
            pbt = PortfolioBacktestEngine(
                eng, bars={("BTC/USDT", "1h"): df}, initial_cash=100_000.0
            )
            result = pbt.run("paper")

            # exactly ONE position-opening trade (crossover fires once)
            buys = [t for t in result.trades if t.side == "buy"]
            assert len(buys) == 1
            buy = buys[0]

            # ── no lookahead: decision uses close[t], fill = open[t+1] ──
            cross_i = _first_cross_index(df)
            decision_expected = (
                df["timestamp"][cross_i].replace(tzinfo=UTC)
                + timedelta(seconds=TF_SEC)
            )
            assert buy.decision_time == decision_expected

            open_next = float(df["open"][cross_i + 1])
            slip = 5.0 / 10_000.0
            assert buy.price == pytest.approx(open_next * (1.0 + slip), rel=1e-12)
            assert buy.fill_time > buy.decision_time  # earliest t+1

            # ── shared-ledger parity, recomputed independently ──
            fee_rate = 10.0 / 10_000.0
            cost = buy.notional + buy.fee
            cash_after_buy = 100_000.0 - cost
            qty = buy.quantity
            final_close = float(df["close"][-1])
            expected_final = cash_after_buy + qty * final_close
            assert result.final_equity == pytest.approx(expected_final, rel=1e-9)

            # equity curve monotone bookkeeping: starts ≈ initial, ends final
            assert result.equity_curve[0][1] == pytest.approx(100_000.0, rel=1e-9)
            assert result.equity_curve[-1][1] == pytest.approx(expected_final, rel=1e-9)

            # promoted artifact actually resolved through the chain
            assert buy.idempotency_key
            # contribution: mtm gain − costs, matches final−initial for N=1
            contrib = result.per_symbol_contribution.get("BTC/USDT")
            assert contrib is not None
            assert (
                result.final_equity - 100_000.0
                == pytest.approx(contrib, rel=1e-6)
            )
        finally:
            eng._graceful_shutdown()

    def test_signal_uses_closed_bar_not_forming_bar(self, config, stores, temp_dir):
        """The decision at time t must never see bar t itself (only < t)."""
        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            art = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="BTC/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            _promote(None, promotion_store, art)
            df = _trend_df(60_000.0)
            clock_bars = {("BTC/USDT", "1h"): df}
            pbt = PortfolioBacktestEngine(
                eng, bars=clock_bars, initial_cash=100_000.0
            )
            cross_i = _first_cross_index(df)
            decision_close_ts = (
                df["timestamp"][cross_i].replace(tzinfo=UTC) + timedelta(hours=1)
            )
            sl = pbt.clock.slice_upto(("BTC/USDT", "1h"), decision_close_ts)
            # last row IS the signal bar (closed at t); nothing beyond it
            assert sl["timestamp"][-1] == df["timestamp"][cross_i]
            assert len(sl) == cross_i + 1
        finally:
            eng._graceful_shutdown()


# ── DoD: N>1 shared-capital test ─────────────────────────────────────────


class TestSharedCapitalMultiPair:
    def test_two_symbols_share_one_pool_under_caps(self, config, stores, temp_dir):
        cfg = AuthorityConfig.for_environment(Environment.PAPER)
        cfg.exposure.max_portfolio_exposure = 0.60
        cfg.exposure.max_single_symbol_exposure = 0.40
        cfg.exposure.max_single_strategy_exposure = 0.40

        rules = {
            "BTC/USDT": _instrument_rules("BTC/USDT"),
            "ETH/USDT": _instrument_rules("ETH/USDT"),
        }
        eng = _build_engine(cfg, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            btc = _make_artifact(
                artifact_store, promotion_store,
                symbol="BTC/USDT", timeframe="1h", fast=10, slow=30,
            )
            eth = _make_artifact(
                artifact_store, promotion_store,
                symbol="ETH/USDT", timeframe="1h", fast=10, slow=30,
            )
            _promote(None, promotion_store, btc)
            _promote(None, promotion_store, eth)

            bars = {
                ("BTC/USDT", "1h"): _trend_df(60_000.0),
                ("ETH/USDT", "1h"): _trend_df(3_000.0, start=datetime(2024, 1, 1, tzinfo=UTC)),
            }
            pbt = PortfolioBacktestEngine(eng, bars=bars, initial_cash=200_000.0)
            result = pbt.run("paper")

            # both symbols traded from the SAME pool
            traded_symbols = {t.symbol for t in result.trades}
            assert traded_symbols == {"BTC/USDT", "ETH/USDT"}

            # every cycle's vector respected the GROSS cap
            for vec in result.target_vectors:
                assert vec.gross_target_exposure <= 0.60 + 1e-9
                for sym, tgt in vec.targets.items():
                    assert tgt <= 0.40 + 1e-9

            # shared cash NEVER goes negative (one pool, two consumers)
            for step in result.steps:
                assert step.cash >= -1e-6

            # synchronized single timeline (union of both grids)
            assert len({s.step_time for s in result.steps}) == len(result.steps)
        finally:
            eng._graceful_shutdown()


# ── DoD: permutation/determinism + replay ────────────────────────────────


class TestDeterminism:
    def _run_with_order(self, config, order):
        """Fully isolated run: fresh stores/state per invocation so repeated
        calls only differ by the BINDING INPUT ORDER."""
        import tempfile

        with tempfile.TemporaryDirectory() as td:
            temp_dir = Path(td)
            from trading_agent.authority.promotion_store import PromotionStateStore
            from trading_agent.research.artifact import PersistentArtifactStore

            promotion_store = PromotionStateStore(temp_dir / "promotion.db")
            artifact_store = PersistentArtifactStore(temp_dir / "artifacts")
            stores = (promotion_store, artifact_store)

            rules = {
                "BTC/USDT": _instrument_rules("BTC/USDT"),
                "ETH/USDT": _instrument_rules("ETH/USDT"),
            }
            eng = _build_engine(config, stores, temp_dir, rules)
            try:
                arts = {}
                for sym, base in (("BTC/USDT", 60_000.0), ("ETH/USDT", 3_000.0)):
                    a = _make_artifact(
                        artifact_store, promotion_store,
                        symbol=sym, timeframe="1h", fast=10, slow=30,
                    )
                    _promote(None, promotion_store, a)
                    arts[sym] = (a, base)
                bars = {
                    (sym, "1h"): _trend_df(base)
                    for sym, (_, base) in arts.items()
                }
                ordered = {b: bars[b] for b in order}
                pbt = PortfolioBacktestEngine(
                    eng, bars=ordered, initial_cash=150_000.0
                )
                return pbt.run("paper").to_dict()
            finally:
                eng._graceful_shutdown()

    def test_binding_permutation_produces_identical_results(
        self, config
    ):
        fwd = self._run_with_order(
            config,
            [("BTC/USDT", "1h"), ("ETH/USDT", "1h")],
        )
        rev = self._run_with_order(
            config,
            [("ETH/USDT", "1h"), ("BTC/USDT", "1h")],
        )
        assert fwd == rev

    def test_replay_produces_identical_result(self, config, stores, temp_dir):
        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            art = _make_artifact(
                artifact_store, promotion_store,
                symbol="BTC/USDT", timeframe="1h", fast=10, slow=30,
            )
            _promote(None, promotion_store, art)
            bars = {("BTC/USDT", "1h"): _trend_df(60_000.0)}
            r1 = PortfolioBacktestEngine(
                eng, bars=bars, initial_cash=100_000.0
            ).run("paper").to_dict()
            r2 = PortfolioBacktestEngine(
                eng, bars=bars, initial_cash=100_000.0
            ).run("paper").to_dict()
            assert r1 == r2
        finally:
            eng._graceful_shutdown()
