"""Milestone D DoD tests — PortfolioBacktestEngine.

Invariant under test: backtest swaps ONLY broker+clock; the whole decision
authority chain (resolver → StrategyRuntime → StrategyOutput → batch
PortfolioAllocator → PortfolioTargetVector → risk/planner/preflight) is the
live pipeline.

Covers the Definition of Done checklist:
- N=1 parity (hand-recomputed ledger math, exact fill price/time, no lookahead)
- N>1 shared capital pool (gross/symbol caps enforced across symbols)
- permutation/determinism (binding order cannot change results)
- replay produces identical results
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import polars as pl
import pytest

pytestmark = [
    pytest.mark.slow,
    pytest.mark.backtest,
]

from tests.test_multi_pair_runtime import (
    _build_engine,
    _instrument_rules,
    _make_artifact,
)
from trading_agent.authority.config import AuthorityConfig, Environment
from trading_agent.backtest.portfolio_backtest import (
    PortfolioBacktestEngine,
    HistoricalSimulationBroker,
    QueuedOrder,
)
from trading_agent.execution.batch_models import wrap_market_data
from trading_agent.execution.multi_pair_runtime import MultiPairRuntime
from trading_agent.research.promotion import ResearchStage

TF_SEC = 3600


# ── deterministic data ───────────────────────────────────────────────────


def _trend_df(
    base: float,
    *,
    n_flat: int = 45,
    n_trend: int = 34,
    growth: float = 1.008,
    start: datetime | None = None,
) -> pl.DataFrame:
    """Flat warmup then steady uptrend → exactly one MA10/30 bullish cross."""
    start = start or datetime(2024, 1, 1, tzinfo=UTC)
    prices = [base] * n_flat
    p = base
    for _ in range(n_trend):
        p *= growth
        prices.append(p)
    stamps = [start + timedelta(hours=i) for i in range(len(prices))]
    return pl.DataFrame(
        {
            "timestamp": stamps,
            "open": prices,
            "high": [x * 1.001 for x in prices],
            "low": [x * 0.999 for x in prices],
            "close": prices,
            "volume": [1000.0] * len(prices),
        }
    )


def _first_cross_index(df: pl.DataFrame, fast: int = 10, slow: int = 30) -> int:
    closes = df["close"].to_list()

    def ma(i: int, w: int) -> float:
        return sum(closes[i - w + 1 : i + 1]) / w

    for i in range(slow - 1, len(closes)):
        f_now, s_now = ma(i, fast), ma(i, slow)
        f_prev, s_prev = ma(i - 1, fast), ma(i - 1, slow)
        if f_prev <= s_prev and f_now > s_now:
            return i
    raise AssertionError("no bullish cross generated by fixture data")


# ── fixtures ─────────────────────────────────────────────────────────────


@pytest.fixture
def temp_dir():
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        yield Path(d)


@pytest.fixture
def stores(temp_dir):
    from trading_agent.authority.promotion_store import PromotionStateStore
    from trading_agent.research.artifact import PersistentArtifactStore

    promotion_store = PromotionStateStore(temp_dir / "promotion.db")
    artifact_store = PersistentArtifactStore(temp_dir / "artifacts")
    return promotion_store, artifact_store


@pytest.fixture
def config() -> AuthorityConfig:
    cfg = AuthorityConfig.for_environment(Environment.PAPER)
    cfg.exposure.max_portfolio_exposure = 0.95
    cfg.exposure.max_single_symbol_exposure = 0.95
    cfg.exposure.max_single_strategy_exposure = 0.95
    return cfg


def _promote(store_artifact, promotion_store, artifact) -> None:
    from trading_agent.authority.promotion_store import PromotionRecord
    from trading_agent.research.promotion import ResearchPromotionEvent

    event = ResearchPromotionEvent(
        subject_artifact_id=artifact.artifact_id,
        from_stage=ResearchStage.RESEARCH_VALIDATED,
        to_stage=ResearchStage.PAPER_ELIGIBLE,
        evidence_ids=("wfo",),
        actor="pbt-test",
        timestamp=datetime.now(UTC),
    )
    promotion_store.upsert(
        PromotionRecord(
            artifact_id=artifact.artifact_id,
            stage=ResearchStage.PAPER_ELIGIBLE,
            latest_event=event,
            updated_at=datetime.now(UTC),
        )
    )


def _make_engine(config, stores, temp_dir, rules):
    eng = _build_engine(config, stores, temp_dir, rules)
    yield eng
    eng._graceful_shutdown()


def _run_btc_only(config, stores, temp_dir, **kw):
    rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
    eng = _build_engine(config, stores, temp_dir, rules)
    try:
        _, artifact_store = stores
        promotion_store = stores[0]
        art = _make_artifact(
            artifact_store,
            promotion_store,
            symbol="BTC/USDT",
            timeframe="1h",
            fast=10,
            slow=30,
        )
        _promote(None, promotion_store, art)
        bars = {("BTC/USDT", "1h"): _trend_df(60_000.0)}
        pbt = PortfolioBacktestEngine(
            eng,
            bars=bars,
            initial_cash=kw.pop("initial_cash", 100_000.0),
            **kw,
        )
        return pbt.run("paper"), eng, art
    finally:
        pass


# ── DoD: PortfolioBacktestEngine exists + N=1 parity ─────────────────────


class TestN1Parity:
    def test_single_binding_full_ledger_math_and_no_lookahead(
        self, config, stores, temp_dir
    ):

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            art = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="BTC/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            _promote(None, promotion_store, art)

            df = _trend_df(60_000.0)
            pbt = PortfolioBacktestEngine(
                eng, bars={("BTC/USDT", "1h"): df}, initial_cash=100_000.0
            )
            result = pbt.run("paper")

            # exactly ONE position-opening trade (crossover fires once)
            buys = [t for t in result.trades if t.side == "buy"]
            assert len(buys) == 1
            buy = buys[0]

            # ── no lookahead: decision uses close[t], fill = open[t+1] ──
            cross_i = _first_cross_index(df)
            decision_expected = df["timestamp"][cross_i].replace(
                tzinfo=UTC
            ) + timedelta(seconds=TF_SEC)
            assert buy.decision_time == decision_expected

            open_next = float(df["open"][cross_i + 1])
            slip = 5.0 / 10_000.0
            assert buy.price == pytest.approx(open_next * (1.0 + slip), rel=1e-12)
            assert buy.fill_time > buy.decision_time  # earliest t+1

            # ── shared-ledger parity, recomputed independently ──
            fee_rate = 10.0 / 10_000.0
            cost = buy.notional + buy.fee
            cash_after_buy = 100_000.0 - cost
            qty = buy.quantity
            final_close = float(df["close"][-1])
            expected_final = cash_after_buy + qty * final_close
            assert result.final_equity == pytest.approx(expected_final, rel=1e-9)

            # equity curve monotone bookkeeping: starts ≈ initial, ends final
            assert result.equity_curve[0][1] == pytest.approx(100_000.0, rel=1e-9)
            assert result.equity_curve[-1][1] == pytest.approx(expected_final, rel=1e-9)

            # promoted artifact actually resolved through the chain
            assert buy.idempotency_key
            # contribution: mtm gain − costs, matches final−initial for N=1
            contrib = result.per_symbol_contribution.get("BTC/USDT")
            assert contrib is not None
            assert result.final_equity - 100_000.0 == pytest.approx(contrib, rel=1e-6)
        finally:
            eng._graceful_shutdown()

    def test_signal_uses_closed_bar_not_forming_bar(self, config, stores, temp_dir):
        """The decision at time t must never see bar t itself (only < t)."""

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            art = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="BTC/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            _promote(None, promotion_store, art)
            df = _trend_df(60_000.0)
            clock_bars = {("BTC/USDT", "1h"): df}
            pbt = PortfolioBacktestEngine(eng, bars=clock_bars, initial_cash=100_000.0)
            cross_i = _first_cross_index(df)
            decision_close_ts = df["timestamp"][cross_i].replace(
                tzinfo=UTC
            ) + timedelta(hours=1)
            sl = pbt.clock.slice_upto(("BTC/USDT", "1h"), decision_close_ts)
            # last row IS the signal bar (closed at t); nothing beyond it
            assert sl["timestamp"][-1] == df["timestamp"][cross_i]
            assert len(sl) == cross_i + 1
        finally:
            eng._graceful_shutdown()


# ── DoD: N>1 shared-capital test ─────────────────────────────────────────


class TestSharedCapitalMultiPair:
    def test_two_symbols_share_one_pool_under_caps(self, config, stores, temp_dir):
        cfg = AuthorityConfig.for_environment(Environment.PAPER)
        cfg.exposure.max_portfolio_exposure = 0.60
        cfg.exposure.max_single_symbol_exposure = 0.40
        cfg.exposure.max_single_strategy_exposure = 0.40

        rules = {
            "BTC/USDT": _instrument_rules("BTC/USDT"),
            "ETH/USDT": _instrument_rules("ETH/USDT"),
        }
        eng = _build_engine(cfg, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            btc = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="BTC/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            eth = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="ETH/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            _promote(None, promotion_store, btc)
            _promote(None, promotion_store, eth)

            bars = {
                ("BTC/USDT", "1h"): _trend_df(60_000.0),
                ("ETH/USDT", "1h"): _trend_df(
                    3_000.0, start=datetime(2024, 1, 1, tzinfo=UTC)
                ),
            }
            pbt = PortfolioBacktestEngine(eng, bars=bars, initial_cash=200_000.0)
            result = pbt.run("paper")

            # both symbols traded from the SAME pool
            traded_symbols = {t.symbol for t in result.trades}
            assert traded_symbols == {"BTC/USDT", "ETH/USDT"}

            # every cycle's vector respected the GROSS cap
            for vec in result.target_vectors:
                assert vec.gross_target_exposure <= 0.60 + 1e-9
                for sym, tgt in vec.targets.items():
                    assert tgt <= 0.40 + 1e-9

            # shared cash NEVER goes negative (one pool, two consumers)
            for step in result.steps:
                assert step.cash >= -1e-6

            # synchronized single timeline (union of both grids)
            assert len({s.step_time for s in result.steps}) == len(result.steps)
        finally:
            eng._graceful_shutdown()


# ── DoD: permutation/determinism + replay ────────────────────────────────


class TestDeterminism:
    def _run_with_order(self, config, order):
        """Fully isolated run: fresh stores/state per invocation so repeated
        calls only differ by the BINDING INPUT ORDER."""
        import tempfile

        with tempfile.TemporaryDirectory() as td:
            temp_dir = Path(td)
            from trading_agent.authority.promotion_store import PromotionStateStore
            from trading_agent.research.artifact import PersistentArtifactStore

            promotion_store = PromotionStateStore(temp_dir / "promotion.db")
            artifact_store = PersistentArtifactStore(temp_dir / "artifacts")
            stores = (promotion_store, artifact_store)

            rules = {
                "BTC/USDT": _instrument_rules("BTC/USDT"),
                "ETH/USDT": _instrument_rules("ETH/USDT"),
            }
            eng = _build_engine(config, stores, temp_dir, rules)
            try:
                arts = {}
                for sym, base in (("BTC/USDT", 60_000.0), ("ETH/USDT", 3_000.0)):
                    a = _make_artifact(
                        artifact_store,
                        promotion_store,
                        symbol=sym,
                        timeframe="1h",
                        fast=10,
                        slow=30,
                    )
                    _promote(None, promotion_store, a)
                    arts[sym] = (a, base)
                bars = {(sym, "1h"): _trend_df(base) for sym, (_, base) in arts.items()}
                ordered = {b: bars[b] for b in order}
                pbt = PortfolioBacktestEngine(eng, bars=ordered, initial_cash=150_000.0)
                return pbt.run("paper").to_dict()
            finally:
                eng._graceful_shutdown()

    def test_binding_permutation_produces_identical_results(self, config):
        fwd = self._run_with_order(
            config,
            [("BTC/USDT", "1h"), ("ETH/USDT", "1h")],
        )
        rev = self._run_with_order(
            config,
            [("ETH/USDT", "1h"), ("BTC/USDT", "1h")],
        )
        assert fwd == rev

    def test_replay_produces_identical_result(self, config, stores, temp_dir):

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            art = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="BTC/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            _promote(None, promotion_store, art)
            bars = {("BTC/USDT", "1h"): _trend_df(60_000.0)}
            r1 = (
                PortfolioBacktestEngine(eng, bars=bars, initial_cash=100_000.0)
                .run("paper")
                .to_dict()
            )
            r2 = (
                PortfolioBacktestEngine(eng, bars=bars, initial_cash=100_000.0)
                .run("paper")
                .to_dict()
            )
            assert r1 == r2
        finally:
            eng._graceful_shutdown()


# ── Milestone D: MultiPairRuntime N=1 vs PortfolioBacktestEngine N=1 ─────


class TestParityLiveCycleVsBacktest:
    """REAL parity: the LIVE batch cycle (MultiPairRuntime.run_cycle with
    broker submission stubbed out) and the historical backtest must produce
    IDENTICAL authority outputs BEFORE the broker boundary — same prepared
    decision inputs, same approved target, same plan quantity.

    Both sides run resolver → strategy → DecisionAuthority → batch
    allocation → ExposureAuthority → planner on the SAME market frame and
    the SAME starting portfolio truth (flat, $100k).
    """

    def test_authority_outputs_identical_before_broker(self, config, stores, temp_dir):
        from tests.test_multi_pair_runtime import _buy_at_last_bar_df
        from trading_agent.execution.batch_models import (
            PlannedAction,
            PlannedSubmissionOutcome,
        )

        binding = ("BTC/USDT", "1h")
        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        df = _buy_at_last_bar_df(60_000.0)  # crossover lands on LAST bar

        # ONE promoted artifact shared by BOTH engines (immutable store)
        promotion_store, artifact_store = stores
        art = _make_artifact(
            artifact_store,
            promotion_store,
            symbol="BTC/USDT",
            timeframe="1h",
            fast=10,
            slow=30,
        )

        # ── LIVE side: MultiPairRuntime with broker boundary stubbed ──
        eng_live = _build_engine(config, stores, temp_dir, rules)
        live_plans: list[Any] = []
        live_prepared: dict[str, Any] = {}
        try:
            original_prepare = eng_live.prepare_promoted_strategy

            def spy_prepare(**kw):
                out = original_prepare(**kw)
                if out is not None and out.prepare_status == "ok":
                    live_prepared[kw["symbol"]] = out
                return out

            eng_live.prepare_promoted_strategy = spy_prepare

            def stub_submit(plan):
                live_plans.append(plan)
                return PlannedSubmissionOutcome(
                    plan=plan,
                    order=object(),  # sentinel: "reached broker"
                    submit_state="ACCEPTED",
                    barrier=False,
                    submitted=True,
                )

            eng_live.submit_planned_order = stub_submit

            runtime = MultiPairRuntime(eng_live)

            def provider(symbol: str, timeframe: str):
                return df if (symbol, timeframe) == binding else None

            report = runtime.run_cycle(
                environment="paper", market_data_provider=provider
            )
        finally:
            eng_live._graceful_shutdown()

        assert len(live_plans) == 1, (
            f"expected exactly one live plan, got {len(live_plans)}; "
            f"report={report.to_dict()}"
        )
        live_plan = live_plans[0]
        assert live_plan.action is PlannedAction.INCREASE
        assert "BTC/USDT" in live_prepared
        assert live_prepared["BTC/USDT"].current_exposure == pytest.approx(0.0)
        assert live_prepared["BTC/USDT"].equity == pytest.approx(100_000.0)

        # ── BACKTEST side: same chain over the historical clock ──
        eng_bt = _build_engine(config, stores, temp_dir, rules)
        bt_plans: list[Any] = []
        try:
            original_plan = eng_bt.plan_pair_order

            def spy_plan(finalized):
                plan = original_plan(finalized)
                bt_plans.append(plan)
                return plan

            eng_bt.plan_pair_order = spy_plan

            pbt = PortfolioBacktestEngine(
                eng_bt, bars={binding: df}, initial_cash=100_000.0
            )
            result = pbt.run("paper")
        finally:
            eng_bt._graceful_shutdown()

        # The signal bar is the LAST bar ⇒ the queued order can never fill;
        # parity is asserted on PLAN outputs (pre-broker), not fills.
        assert len(bt_plans) == 1, f"expected one backtest plan, got {bt_plans}"
        bt_plan = bt_plans[0]
        assert bt_plan.action is PlannedAction.INCREASE
        assert result.expired_orders == 1  # stayed queued past data end

        # ── PARITY: authority outputs identical before broker boundary ──
        lp, bp = live_plan, bt_plan
        lp_prep = lp.finalized.prepared
        bp_prep = bp.finalized.prepared

        # decision inputs from portfolio truth
        assert lp_prep.current_exposure == pytest.approx(
            bp_prep.current_exposure, abs=1e-12
        )
        assert lp_prep.equity == pytest.approx(bp_prep.equity, rel=1e-12)
        assert lp_prep.available_cash == pytest.approx(
            bp_prep.available_cash, rel=1e-12
        )
        assert lp_prep.total_portfolio_exposure == pytest.approx(
            bp_prep.total_portfolio_exposure, abs=1e-12
        )
        assert lp_prep.current_price == pytest.approx(bp_prep.current_price, rel=1e-12)

        # risk decision semantics
        assert bool(lp_prep.risk_decision.reduce_only) == bool(
            bp_prep.risk_decision.reduce_only
        )
        assert lp_prep.risk_decision.requested_target_exposure == pytest.approx(
            bp_prep.risk_decision.requested_target_exposure, rel=1e-12
        )

        # approved target after batch allocation
        assert lp.finalized.approved_target_exposure == pytest.approx(
            bp.finalized.approved_target_exposure, rel=1e-12
        )

        # planned order quantity (same math both sides ⇒ near-exact)
        assert lp.quantity == pytest.approx(bp.quantity, rel=1e-9)
        assert float(lp.quantity) > 0

    def test_snapshot_injection_changes_decision_inputs(self, config, stores, temp_dir):
        """prepare_promoted_strategy(portfolio_snapshot=...) must derive
        current position / equity / cash from the snapshot, NOT live state.
        """
        from tests.test_multi_pair_runtime import _buy_at_last_bar_df
        from trading_agent.authority.portfolio import (
            PortfolioSnapshot,
            ReconciliationState,
        )

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            promotion_store, artifact_store = stores
            art = _make_artifact(
                artifact_store,
                promotion_store,
                symbol="BTC/USDT",
                timeframe="1h",
                fast=10,
                slow=30,
            )
            df = _buy_at_last_bar_df(60_000.0)

            snapshot = PortfolioSnapshot(
                equity=250_000.0,  # ≠ live paper equity (100k)
                available_cash=40_000.0,  # ≠ live paper cash
                positions={"ETH/USDT": 3.0},  # ≠ live positions ({})
                symbol_exposures={"ETH/USDT": 0.36},
                gross_exposure=0.36,
                reconciliation_state=ReconciliationState.RECONCILED,
            )

            prepared = eng.prepare_promoted_strategy(
                symbol="BTC/USDT",
                timeframe="1h",
                environment="paper",
                market_data_input=wrap_market_data(
                    "BTC/USDT", "1h", df, source="parity-test"
                ),
                portfolio_snapshot=snapshot,
            )
            assert prepared is not None and prepared.prepare_status == "ok"
            assert prepared.equity == pytest.approx(250_000.0)
            assert prepared.available_cash == pytest.approx(40_000.0)
            assert prepared.total_portfolio_exposure == pytest.approx(0.36)
            assert prepared.current_quantity == pytest.approx(0.0)  # BTC flat in snap
        finally:
            eng._graceful_shutdown()


# ── Broker execution phases + queued reservations ────────────────────────


class TestBrokerPhaseAndReservations:
    def _flat_df(self, n: int = 8, price: float = 100.0) -> pl.DataFrame:
        start = datetime(2024, 1, 1, tzinfo=UTC)
        stamps = [start + timedelta(hours=i) for i in range(n)]
        return pl.DataFrame(
            {
                "timestamp": stamps,
                "open": [price] * n,
                "high": [price] * n,
                "low": [price] * n,
                "close": [price] * n,
                "volume": [10.0] * n,
            }
        )

    def _q(self, key, side, qty, dt, phase=None, ref=100.0, symbol="BTC/USDT"):
        from trading_agent.backtest.portfolio_backtest import QueuedOrder

        return QueuedOrder(
            idempotency_key=key,
            symbol=symbol,
            side=side,
            quantity=qty,
            reference_price=ref,
            decision_time=dt,
            **({"phase": phase} if phase else {}),
        )

    def test_reduction_settles_before_increase(self, config, stores, temp_dir):
        from trading_agent.backtest.portfolio_backtest import (
            HistoricalSimulationBroker,
        )

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            df = self._flat_df()
            pbt = PortfolioBacktestEngine(
                eng, bars={("BTC/USDT", "1h"): df}, initial_cash=100.0
            )
            broker = HistoricalSimulationBroker(100.0, fee_bps=10.0, slippage_bps=5.0)
            clock = pbt.clock
            dt = df["timestamp"][2]  # fills at bar[3] open

            # seed a long so the reduction SELL is fillable + frees cash
            broker.positions["BTC/USDT"] = {"qty": 1.0, "avg_px": 100.0}

            # INCREASE queued EARLIER but must settle AFTER the reduction
            broker.queue(self._q("b1", "buy", 1.0, dt))
            broker.queue(self._q("s1", "sell", 1.0, dt, phase="reduction"))

            fills = broker.settle(df["timestamp"][3], clock, [("BTC/USDT", "1h")])
            assert [f.side for f in fills] == ["sell", "buy"], (
                "REDUCTION must settle before INCREASE"
            )
            # freed sell cash made the buy affordable: cash stays positive
            assert broker.cash > 0
            assert broker.pending_count == 0
        finally:
            eng._graceful_shutdown()

    def test_reserved_cash_and_inventory_count_pending(self, config, stores, temp_dir):
        from trading_agent.backtest.portfolio_backtest import (
            HistoricalSimulationBroker,
        )

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            df = self._flat_df()
            pbt = PortfolioBacktestEngine(
                eng, bars={("BTC/USDT", "1h"): df}, initial_cash=100.0
            )
            broker = HistoricalSimulationBroker(100.0, fee_bps=10.0, slippage_bps=5.0)
            dt = df["timestamp"][2]
            broker.queue(self._q("b1", "buy", 2.0, dt, ref=50.0))
            broker.queue(self._q("s1", "sell", 0.5, dt))

            est_notional = 2.0 * 50.0
            expected_reserved = est_notional * (1 + 10.0 / 10_000.0 + 5.0 / 10_000.0)
            assert broker.reserved_cash() == pytest.approx(expected_reserved)
            assert broker.reserved_inventory("BTC/USDT") == pytest.approx(0.5)
            assert broker.reserved_inventory("ETH/USDT") == 0.0

            # nothing eligible to fill yet (settle BEFORE dt's next bar)
            fills = broker.settle(df["timestamp"][2], pbt.clock, [("BTC/USDT", "1h")])
            assert fills == []
            # reservations persist while orders stay queued
            assert broker.reserved_cash() == pytest.approx(expected_reserved)
        finally:
            eng._graceful_shutdown()

    def test_snapshot_reflects_reservations(self, config, stores, temp_dir):
        """Snapshot must hide reserved inventory/cash from decisions while
        marking equity on FULL holdings."""
        from trading_agent.authority.config import Environment
        from trading_agent.authority.portfolio import ReconciliationState as RS
        from trading_agent.backtest.portfolio_backtest import (
            HistoricalSimulationBroker,
        )

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        try:
            df = self._flat_df(price=200.0)
            pbt = PortfolioBacktestEngine(
                eng, bars={("BTC/USDT", "1h"): df}, initial_cash=100.0
            )
            broker = HistoricalSimulationBroker(100.0)
            broker.cash = 50_000.0
            broker.positions["BTC/USDT"] = {"qty": 2.0, "avg_px": 200.0}
            dt = df["timestamp"][2]
            broker.queue(self._q("s1", "sell", 0.5, dt, phase="reduction"))
            broker.queue(self._q("b1", "buy", 1.0, dt, ref=200.0))

            snap = pbt._build_snapshot(df["timestamp"][4], broker, Environment.PAPER)

            # effective inventory = held − pending sell
            assert snap.positions["BTC/USDT"] == pytest.approx(1.5)
            # equity marked on FULL held qty at last close
            assert snap.equity == pytest.approx(50_000.0 + 2.0 * 200.0)
            # available cash net of pending-buy reservation
            expected_reserved = 1.0 * 200.0 * (1 + 10e-4 + 5e-4)
            assert snap.available_cash == pytest.approx(50_000.0 - expected_reserved)
            assert snap.reserved_cash == pytest.approx(expected_reserved)
            assert snap.reserved_inventory == pytest.approx(0.5)
            # exposure computed off EFFECTIVE qty
            assert snap.symbol_exposures["BTC/USDT"] == pytest.approx(
                1.5 * 200.0 / snap.equity
            )
            assert snap.reconciliation_state is RS.RECONCILED
        finally:
            eng._graceful_shutdown()


# ── Actual-fill safety guards (P0 execution safety) ──────────────────────


class TestBrokerFillSafetyGuards:
    """Guarantees on ACTUAL fills (not planning reservations):
    no negative cash, no synthetic proceeds, aggregate-spend safety,
    reservation-estimate < actual-cost determinism."""

    def _df(self, levels, n_gap=2, base_open=100.0):
        """Bars: flat at 100 then GAP to ``levels`` on bar[gap_index]."""
        start = datetime(2024, 1, 1, tzinfo=UTC)
        prices = [base_open] * n_gap + levels
        # ensure unique open timestamps, ascending
        stamps = [start + timedelta(hours=i) for i in range(len(prices))]
        return pl.DataFrame(
            {
                "timestamp": stamps,
                "open": prices,
                "high": prices,
                "low": prices,
                "close": prices,
                "volume": [10.0] * len(prices),
            }
        )

    def _setup(self, config, stores, temp_dir, prices_df, cash):
        from trading_agent.backtest.portfolio_backtest import (
            HistoricalSimulationBroker,
        )

        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        pbt = PortfolioBacktestEngine(
            eng, bars={("BTC/USDT", "1h"): prices_df}, initial_cash=100.0
        )
        broker = HistoricalSimulationBroker(cash, fee_bps=10.0, slippage_bps=5.0)
        return eng, pbt, broker

    def _q(self, key, side, qty, dt, phase=None, ref=100.0):
        from trading_agent.backtest.portfolio_backtest import QueuedOrder

        return QueuedOrder(
            idempotency_key=key,
            symbol="BTC/USDT",
            side=side,
            quantity=qty,
            reference_price=ref,
            decision_time=dt,
            phase=phase,
        )

    def test_gap_up_buy_never_negative_cash(self, config, stores, temp_dir):
        df = self._df(levels=[200.0, 200.0], n_gap=2, base_open=100.0)
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=105.0)
        try:
            # reserve-based estimate ~100.15 fit; ACTUAL gap open=200 ⇒ cost ~201
            broker.queue(self._q("buy1", "buy", 1.0, df["timestamp"][2], ref=100.0))
            fills = broker.settle(df["timestamp"][3], pbt.clock, [("BTC/USDT", "1h")])
            assert fills == []  # rejected
            assert broker.cash == pytest.approx(105.0)  # untouched
            assert broker.pending_count == 0  # DROPPED permanently
            assert broker.reserved_cash() == 0.0
            assert broker.cash >= 0.0
        finally:
            eng._graceful_shutdown()

    def test_oversized_sell_no_synthetic_proceeds(self, config, stores, temp_dir):
        # 4 flat bars at 100; SELL 5 lots but only hold 1
        df = self._df(levels=[100.0, 100.0, 100.0, 100.0], n_gap=0, base_open=100.0)
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=1.0)
        try:
            broker.positions["BTC/USDT"] = {"qty": 1.0, "avg_px": 100.0}
            # queue SELL 5.0 at bar[2] open (decision_time=bar1)
            broker.queue(
                self._q("s1", "sell", 5.0, df["timestamp"][1], phase="reduction")
            )
            fills = broker.settle(df["timestamp"][2], pbt.clock, [("BTC/USDT", "1h")])
            assert len(fills) == 1
            f = fills[0]
            assert f.quantity == pytest.approx(1.0)  # capped to held
            # proceeds ONLY from 1 lot (sell proceeds minus fee), no synthetic
            raw = 100.0
            price = raw * (1 - 0.0005)
            expected_proceeds = price - price * 0.001
            assert broker.cash == pytest.approx(1.0 + expected_proceeds)
            assert broker.positions["BTC/USDT"]["qty"] == pytest.approx(0.0)
            assert broker.pending_count == 0  # remainder discarded
        finally:
            eng._graceful_shutdown()

    def test_two_buys_same_fill_timestamp_aggregate(self, config, stores, temp_dir):
        # df: [100,100,100], 3 hourly bars; fill at ts[2]
        df = self._df(levels=[100.0, 100.0], n_gap=1, base_open=100.0)
        # cost each: 1*100*1.0005 + fee(1*100*1.0005*0.001) ≈ 100.15005
        cash = 100.15005 + 0.01  # covers exactly one
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=cash)
        try:
            broker.queue(self._q("b1", "buy", 1.0, df["timestamp"][1], ref=100.0))
            broker.queue(self._q("b2", "buy", 1.0, df["timestamp"][1], ref=100.0))
            fills = broker.settle(df["timestamp"][2], pbt.clock, [("BTC/USDT", "1h")])
            assert len(fills) == 1
            assert fills[0].idempotency_key == "b1"
            raw = 100.0
            price = raw * (1 + 0.0005)  # BUY slips up
            one_buy_cost = price + price * 0.001  # notional + fee
            expected_cash = cash - one_buy_cost
            assert broker.cash == pytest.approx(expected_cash, abs=1e-9)
            assert broker.cash >= 0.0
            assert broker.pending_count == 0  # second DROPPED permanently
        finally:
            eng._graceful_shutdown()

    def test_reservation_undershoot_actual_cost_deterministic(
        self, config, stores, temp_dir
    ):
        """Reservation estimate (ref price based) < actual fill cost (gap)
        ⇒ guard rejects deterministically, cash never negative."""
        df = self._df(levels=[105.0, 105.0], n_gap=2, base_open=100.0)
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=101.0)
        try:
            # reservation estimate: 1*100*(1+slip+fee) ≈ 100.15 → snapshot
            # available_cash = 101 − 100.15 > 0 ⇒ planning APPROVES.
            # ACTUAL: 1*105*1.005 + fee ≈ 105.78 > 101 ⇒ guard rejects.
            broker.queue(self._q("buy1", "buy", 1.0, df["timestamp"][2], ref=100.0))
            reserved = broker.reserved_cash()
            assert reserved == pytest.approx(100.0 * 1.0015)  # ~100.15
            assert (101.0 - reserved) > 0  # planning approves
            fills = broker.settle(df["timestamp"][3], pbt.clock, [("BTC/USDT", "1h")])
            assert fills == []
            assert broker.cash == pytest.approx(101.0)
            assert broker.positions.get("BTC/USDT", {}).get("qty", 0.0) == 0.0
        finally:
            eng._graceful_shutdown()


# ── Order rejection = permanent drop (P0 safety) ─────────────────────────


class TestBrokerRejectionDrop:
    """Rejected orders are DROPPED permanently, not re-queued.
    Covers: gap-up BUY drop, stale rejected BUY never fills on price drop,
    zero-inventory SELL drop, stale rejected SELL never touches new inventory."""

    def _df_flat(self, n: int = 8, price: float = 100.0) -> pl.DataFrame:
        start = datetime(2024, 1, 1, tzinfo=UTC)
        stamps = [start + timedelta(hours=i) for i in range(n)]
        return pl.DataFrame(
            {
                "timestamp": stamps,
                "open": [price] * n,
                "high": [price] * n,
                "low": [price] * n,
                "close": [price] * n,
                "volume": [10.0] * n,
            }
        )

    def _df_gap(self, levels, n_gap=2, base_open=100.0):
        start = datetime(2024, 1, 1, tzinfo=UTC)
        prices = [base_open] * n_gap + levels
        stamps = [start + timedelta(hours=i) for i in range(len(prices))]
        return pl.DataFrame(
            {
                "timestamp": stamps,
                "open": prices,
                "high": prices,
                "low": prices,
                "close": prices,
                "volume": [10.0] * len(prices),
            }
        )

    def _setup(self, config, stores, temp_dir, df, cash):
        rules = {"BTC/USDT": _instrument_rules("BTC/USDT")}
        eng = _build_engine(config, stores, temp_dir, rules)
        pbt = PortfolioBacktestEngine(
            eng, bars={("BTC/USDT", "1h"): df}, initial_cash=100.0
        )
        broker = HistoricalSimulationBroker(cash, fee_bps=10.0, slippage_bps=5.0)
        return eng, pbt, broker

    def _q(self, key, side, qty, dt, phase=None, ref=100.0):
        return QueuedOrder(
            idempotency_key=key,
            symbol="BTC/USDT",
            side=side,
            quantity=qty,
            reference_price=ref,
            decision_time=dt,
            phase=phase,
        )

    def test_gap_up_buy_dropped_not_queued(self, config, stores, temp_dir):
        """Gap-up BUY rejected → pending_count == 0, reserved_cash == 0."""
        # flat 100 then GAP to 200 at bar[2]
        df = self._df_gap(levels=[200.0, 200.0], n_gap=2, base_open=100.0)
        # cash only ~105, actual cost ~201
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=105.0)
        try:
            # decision at bar[2] (gap bar open), fill would be at bar[2] open=200
            broker.queue(self._q("buy1", "buy", 1.0, df["timestamp"][2], ref=100.0))
            assert broker.pending_count == 1
            fills = broker.settle(df["timestamp"][3], pbt.clock, [("BTC/USDT", "1h")])
            assert fills == []  # rejected
            assert broker.pending_count == 0  # DROPPED
            assert broker.reserved_cash() == 0.0
            assert broker.cash == pytest.approx(105.0)
        finally:
            eng._graceful_shutdown()

    def test_rejected_buy_never_fills_on_price_drop(self, config, stores, temp_dir):
        """Rejected BUY + later price drop → old order NEVER fills."""
        df = self._df_gap(levels=[200.0, 90.0, 90.0, 90.0], n_gap=2, base_open=100.0)
        # first gap UP to 200 (rejects), then drop to 90
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=105.0)
        try:
            # decision at bar[2] (gap bar open=200), fill at bar[2] → rejected
            broker.queue(self._q("buy1", "buy", 1.0, df["timestamp"][2], ref=100.0))
            fills = broker.settle(df["timestamp"][3], pbt.clock, [("BTC/USDT", "1h")])
            assert fills == []
            assert broker.pending_count == 0  # dropped

            # later: price dropped to 90 at bar[3]; old order must NOT fill
            fills2 = broker.settle(df["timestamp"][4], pbt.clock, [("BTC/USDT", "1h")])
            assert fills2 == []
            assert broker.positions.get("BTC/USDT", {}).get("qty", 0.0) == 0.0
            assert broker.cash == pytest.approx(105.0)
        finally:
            eng._graceful_shutdown()

    def test_zero_inventory_sell_dropped(self, config, stores, temp_dir):
        """SELL with zero inventory rejected → pending_count == 0."""
        df = self._df_flat()
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=1.0)
        try:
            broker.queue(
                self._q("s1", "sell", 5.0, df["timestamp"][1], phase="reduction")
            )
            assert broker.pending_count == 1
            fills = broker.settle(df["timestamp"][2], pbt.clock, [("BTC/USDT", "1h")])
            assert fills == []
            assert broker.pending_count == 0  # DROPPED
            assert broker.reserved_inventory("BTC/USDT") == 0.0
            assert broker.cash == pytest.approx(1.0)
        finally:
            eng._graceful_shutdown()

    def test_rejected_sell_never_touches_new_inventory(self, config, stores, temp_dir):
        """Rejected old SELL + later new BUY position → stale SELL NEVER touches new inventory."""
        df = self._df_flat()
        eng, pbt, broker = self._setup(config, stores, temp_dir, df, cash=500.0)
        try:
            # queue SELL with NO inventory → rejected & dropped
            broker.queue(
                self._q("s1", "sell", 5.0, df["timestamp"][1], phase="reduction")
            )
            fills = broker.settle(df["timestamp"][2], pbt.clock, [("BTC/USDT", "1h")])
            assert fills == []
            assert broker.pending_count == 0  # dropped

            # later: BUY builds a new position
            broker.queue(self._q("b1", "buy", 3.0, df["timestamp"][2]))
            fills = broker.settle(df["timestamp"][3], pbt.clock, [("BTC/USDT", "1h")])
            assert len(fills) == 1
            assert fills[0].side == "buy"
            assert fills[0].quantity == pytest.approx(3.0)

            # old rejected SELL must NOT touch the new 3.0 inventory
            # (it was dropped, so no more orders queued)
            assert broker.pending_count == 0
            assert broker.positions["BTC/USDT"]["qty"] == pytest.approx(3.0)

            # even if we manually settle again, nothing happens
            fills2 = broker.settle(df["timestamp"][4], pbt.clock, [("BTC/USDT", "1h")])
            assert fills2 == []
            assert broker.positions["BTC/USDT"]["qty"] == pytest.approx(3.0)
        finally:
            eng._graceful_shutdown()
