"""Canonical strategy tournament (Phase S2).

Runs ``strategy × pair × parameters × cost-scenario`` cells through the
*same* full execution path as :mod:`scripts.full_system_backtest`
(ExecutionEngine authority chain, RiskController, protective orders,
lifecycle event store) with exactly one difference per cell: the signal
series is generated by the canonical
``ForecastStrategy.forecast(MarketObservation)`` contract via the
allowlisted, hash-verified registry — never by ad-hoc strategy code.

Fail-closed guarantees (STR-0208/0209):

- Only registry allowlisted strategies can be evaluated.
- Every cell writes to its own state dir / report path / manifest.
- A cell missing any required metric (or carrying non-finite values) is
  recorded as ``FAILED`` — missing evidence is NEVER defaulted to 0.
- Terminal-state hygiene is inherited from the simulator's
  ``execution_health`` block (unknown/manual/unprotected must all be zero).
"""

from __future__ import annotations

import hashlib
import json
import math
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS_DIR = ROOT / "scripts"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import polars as pl

from trading_agent.backtest.reporting import (
    assess_ohlcv,
    calculate_cost_attribution,
    calendar_returns,
)
from trading_agent.data.storage import load_ohlcv
from trading_agent.strategies.canonical.adapter import (
    ACTION_BUY,
    ACTION_SELL,
    LegacyDataFrameAdapter,
)
from trading_agent.strategies.canonical.candidates import build_default_registry
from trading_agent.strategies.canonical.descriptor import StrategyDescriptor
from trading_agent.strategies.canonical.features import (
    FEATURE_OHLCV_WINDOW,
    FeatureUnavailableError,
    build_ohlcv_window,
)
from trading_agent.strategies.canonical.registry import (
    RegistryIntegrityError,
    UnknownStrategyError,
)

# Base paper cost model (mirrors PaperExchange defaults used everywhere else).
BASE_COMMISSION = 0.001
BASE_SLIPPAGE = 0.0005


@dataclass(frozen=True)
class CostScenario:
    """Fee/slippage multipliers applied on top of the base cost model."""

    name: str
    fee_multiplier: float = 1.0
    slippage_multiplier: float = 1.0

    def __post_init__(self) -> None:
        for value in (self.fee_multiplier, self.slippage_multiplier):
            if not math.isfinite(value) or value <= 0:
                raise ValueError("cost multipliers must be positive and finite")

    @property
    def commission(self) -> float:
        return BASE_COMMISSION * self.fee_multiplier

    @property
    def slippage(self) -> float:
        return BASE_SLIPPAGE * self.slippage_multiplier

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "fee_multiplier": self.fee_multiplier,
            "slippage_multiplier": self.slippage_multiplier,
        }


#: Canonical scenario set (STR-0205).
SCENARIO_BASE = CostScenario("1x")
SCENARIO_DOUBLE = CostScenario("2x", fee_multiplier=2.0, slippage_multiplier=2.0)
SCENARIO_TRIPLE = CostScenario("3x", fee_multiplier=3.0, slippage_multiplier=3.0)
SCENARIO_SLIPPAGE_STRESS = CostScenario(
    "slip_stress", fee_multiplier=1.0, slippage_multiplier=5.0
)
DEFAULT_SCENARIOS = (
    SCENARIO_BASE,
    SCENARIO_DOUBLE,
    SCENARIO_SLIPPAGE_STRESS,
)


# ── STR-0206 fault scenarios ───────────────────────────────────────────────


@dataclass(frozen=True)
class FaultProfile:
    """Deterministic execution-fault injection for one tournament cell.

    Every field is an independent knob; the runner applies the combined
    schedule to the SAME execution path so fault runs measure resilience,
    never a different code path.
    """

    name: str = "none"
    #: Drop every k-th bar from the source frame (data gaps).
    drop_gap_bars_every: int = 0
    #: Number of stale-price windows; each freezes the venue feed for
    #  ``stale_window_bars`` consecutive bars starting at multiples of
    #  ``stale_window_stride``.
    stale_windows: int = 0
    stale_window_bars: int = 5
    stale_window_stride: int = 200
    #: Reject the first N order placements with a broker error.
    reject_first_n_orders: int = 0
    #: Market orders fill only this fraction of the requested amount.
    partial_fill_fraction: float = 1.0
    #: First protective-order cancel is silently missed (cancel race).
    cancel_miss_first: bool = False
    #: Every stop-loss placement fails (protection outage).
    break_protection: bool = False

    def __post_init__(self) -> None:
        if self.drop_gap_bars_every < 0 or self.stale_windows < 0:
            raise ValueError("fault counts must be non-negative")
        if not 0.0 < self.partial_fill_fraction <= 1.0:
            raise ValueError("partial_fill_fraction must be in (0, 1]")
        if self.reject_first_n_orders < 0:
            raise ValueError("reject_first_n_orders must be non-negative")

    @property
    def active(self) -> bool:
        return self != FAULT_NONE


FAULT_NONE = FaultProfile()
FAULT_GAP_EVERY_50 = FaultProfile("gap50", drop_gap_bars_every=50)
FAULT_STALE_FEED = FaultProfile("stale", stale_windows=3)
FAULT_REJECT_FIRST_2 = FaultProfile("reject2", reject_first_n_orders=2)
FAULT_PARTIAL_HALF = FaultProfile("partial_half", partial_fill_fraction=0.5)
FAULT_CANCEL_RACE = FaultProfile("cancel_race", cancel_miss_first=True)
FAULT_PROTECTION_OUTAGE = FaultProfile("protect_outage", break_protection=True)

ALL_FAULT_PROFILES = (
    FAULT_NONE,
    FAULT_GAP_EVERY_50,
    FAULT_STALE_FEED,
    FAULT_REJECT_FIRST_2,
    FAULT_PARTIAL_HALF,
    FAULT_CANCEL_RACE,
    FAULT_PROTECTION_OUTAGE,
)


def apply_faults(simulator: Any, profile: FaultProfile) -> None:
    """Wrap exchange/engine hooks on a constructed simulator (in place).

    Faults are injected at the paper exchange level but designed to flow
    through the canonical lifecycle properly (REJECTED orders, partial fills
    with protective stops, cancel races tracked via lifecycle).
    """
    if not profile.active:
        return

    exchange = simulator.engine.exchange
    from trading_agent.execution.paper_exchange import OrderStatus

    # ── Reject first N orders (market orders filled immediately, limit/stop pending) ────
    if profile.reject_first_n_orders:
        state = {"rejected": 0}
        original_fill_market = exchange._fill_market_order

        def rejecting_fill(order_id: str):
            if state["rejected"] < profile.reject_first_n_orders:
                state["rejected"] += 1
                order = exchange.orders.get(order_id)
                if order:
                    order.status = OrderStatus.REJECTED
                    exchange._save_state()
                return
            return original_fill_market(order_id)

        exchange._fill_market_order = rejecting_fill

    # ── Break protection (stop-loss placement fails) ────────────────────────
    if profile.break_protection:
        original_place = exchange.place_order

        def placing(
            symbol: str,
            side: Any,
            order_type: Any,
            amount: float = 0.0,
            price: float | None = None,
            stop_price: float | None = None,
            idempotency_key: str | None = None,
            client_order_id: str | None = None,
        ):
            order_type_str = str(order_type).lower()
            is_stop = "stop" in order_type_str
            order = original_place(
                symbol=symbol,
                side=side,
                order_type=order_type,
                amount=amount,
                price=price,
                stop_price=stop_price,
                idempotency_key=idempotency_key,
                client_order_id=client_order_id,
            )
            if is_stop:
                # Stop order placed but broker rejects it
                order.status = OrderStatus.REJECTED
                exchange._save_state()
            return order

        exchange.place_order = placing

    # ── Partial fills (market orders only fill fraction) ────────────────────
    # Apply only to BUY (entry) orders — SELL (exit) orders fill fully to
    # avoid residual unprotected positions. This models realistic broker
    # behavior where entry orders are more likely to be partially filled.
    if profile.partial_fill_fraction < 1.0:
        original_fill = exchange._fill_market_order

        def partial_fill(order_id: str):
            order = exchange.orders.get(order_id)
            if order is None:
                return original_fill(order_id)
            # Only partially fill BUY orders (entry); SELL orders fill fully
            # to close positions cleanly and avoid residual unprotected qty.
            from trading_agent.execution.paper_exchange import OrderSide

            if order.side == OrderSide.BUY:
                real_amount = order.amount
                try:
                    order.amount = real_amount * profile.partial_fill_fraction
                    return original_fill(order_id)
                finally:
                    order.amount = real_amount
            return original_fill(order_id)

        exchange._fill_market_order = partial_fill

    # ── Cancel race (first cancel reported as lost by venue) ───────────────
    if profile.cancel_miss_first:
        original_cancel = exchange.cancel_order
        state = {"missed": False}

        def cancelling(order_id: str):
            result = original_cancel(order_id)
            if not state["missed"] and result is not None:
                state["missed"] = True
                order = exchange.orders.get(order_id)
                if order is not None:
                    order.status = OrderStatus.OPEN
                return None
            return result

        exchange.cancel_order = cancelling

    # ── Stale price feed (already works correctly) ─────────────────────────
    if profile.stale_windows:
        original_update = simulator.engine.update_prices

        def stale_update(prices: dict[str, float]):
            now = getattr(rc_clock(), "current", None)
            if now is None:
                return original_update(prices)
            for start in simulator._stale_starts:
                if (
                    start
                    <= now
                    < start + simulator.timeframe_delta * profile.stale_window_bars
                ):
                    return
            return original_update(prices)

        simulator.engine.update_prices = stale_update

    # ── Data gaps: record in manifest, don't drop bars (breaks simulator) ───
    if profile.drop_gap_bars_every:
        pass  # Handled in run_cell() data loading


def rc_clock():
    """Access the simulator's fake clock class (monkeypatched in scripts)."""
    import sys

    module = sys.modules.get("scripts.full_system_backtest")
    if module is None:
        raise RuntimeError("full_system_backtest module is not imported")
    return module._SimClock


@dataclass(frozen=True)
class EvaluationCellSpec:
    """One tournament cell: strategy × symbol × params × cost × faults."""

    strategy_id: str
    symbol: str
    timeframe: str = "1h"
    params: Mapping[str, Any] = field(default_factory=dict)
    cost_scenario: CostScenario = SCENARIO_BASE
    fault: FaultProfile = FAULT_NONE

    def __post_init__(self) -> None:
        if not self.strategy_id or not self.symbol:
            raise ValueError("strategy_id and symbol are required")
        object.__setattr__(
            self, "params", MappingProxyType(dict(sorted(self.params.items())))
        )

    @property
    def params_hash(self) -> str:
        payload = json.dumps(dict(self.params), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(payload.encode()).hexdigest()[:12]

    @property
    def cell_id(self) -> str:
        safe_symbol = self.symbol.replace("/", "")
        base = (
            f"{self.strategy_id}__{safe_symbol}__{self.timeframe}"
            f"__{self.cost_scenario.name}__p{self.params_hash}"
        )
        if self.fault.active:
            base += f"__f{self.fault.name}"
        return base


def canonical_signal_series(
    adapter: LegacyDataFrameAdapter,
    frame: pl.DataFrame,
    *,
    warmup_bars: int,
    symbol: str,
) -> list[int]:
    """Per-bar deterministic signals from the canonical contract.

    Signal at index j is decided on the bar closed at time[j] (window ends
    strictly before j) and is executed at bar j+1's open by the simulator —
    decision-on-closed-bar / execute-next-open (STR-0203).
    """
    if "time" not in frame.columns:
        raise ValueError("frame must carry a 'time' column")
    times = frame["time"].to_list()
    # Storage timestamps may be tz-naive; the contract requires awareness.
    if times and getattr(times[0], "tzinfo", None) is None:
        times = [value.replace(tzinfo=UTC) for value in times]
    signals = [0] * frame.height
    for j in range(warmup_bars + 1, len(frame)):
        observed_at = times[j]
        try:
            window = build_ohlcv_window(
                frame.head(j),
                observed_at=observed_at,
                bars=warmup_bars + 1,
            )
        except FeatureUnavailableError:
            continue  # insufficient history at this bar → stay flat
        row = frame.row(j, named=True)
        observation = _market_observation(symbol, observed_at, row, window)
        forecast = adapter.forecast(observation)
        action = forecast.metadata.get("canonical_action")
        if action == ACTION_BUY:
            signals[j] = 1
        elif action == ACTION_SELL:
            signals[j] = -1
    return signals


def _market_observation(strategy_id, observed_at, row, window):
    from trading_agent.research.forecast import MarketObservation

    return MarketObservation(
        symbol=strategy_id.split(":")[0],
        observed_at=observed_at,
        open=float(row["open"]),
        high=float(row["high"]),
        low=float(row["low"]),
        close=float(row["close"]),
        volume=float(row.get("volume", 0.0)),
        features={FEATURE_OHLCV_WINDOW: window},
    )


@dataclass(frozen=True)
class EvaluationArtifact:
    """Content-addressed result of one tournament cell (STR-0207)."""

    cell_id: str
    status: str  # COMPLETED | FAILED
    descriptor_id: str
    strategy_id: str
    symbol: str
    timeframe: str
    params_hash: str
    cost_scenario: str
    fault_profile: str
    commission: float
    slippage: float
    data_manifest_sha: str
    commit_sha: str
    report_path: str | None
    metrics: Mapping[str, Any]
    execution_health: Mapping[str, Any]
    failure_reasons: tuple[str, ...] = ()
    created_at: str = ""
    measurement_window: tuple[int, int] | None = None
    simulation_window: tuple[int, int | None] | None = None
    signal_delay_bars: int = 0
    selection_freeze_id: str | None = None

    @property
    def artifact_id(self) -> str:
        payload = json.dumps(
            {
                "cell_id": self.cell_id,
                "status": self.status,
                "descriptor_id": self.descriptor_id,
                "strategy_id": self.strategy_id,
                "symbol": self.symbol,
                "timeframe": self.timeframe,
                "params_hash": self.params_hash,
                "cost_scenario": self.cost_scenario,
                "fault_profile": self.fault_profile,
                "commission": self.commission,
                "slippage": self.slippage,
                "data_manifest_sha": self.data_manifest_sha,
                "commit_sha": self.commit_sha,
                "report_path": self.report_path,
                "measurement_window": self.measurement_window,
                "simulation_window": self.simulation_window,
                "signal_delay_bars": self.signal_delay_bars,
                "selection_freeze_id": self.selection_freeze_id,
                "metrics": dict(self.metrics),
                "execution_health": dict(self.execution_health),
                "failure_reasons": self.failure_reasons,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
        return f"sha256:{hashlib.sha256(payload.encode()).hexdigest()}"

    def to_dict(self) -> dict[str, Any]:
        return {
            "artifact_id": self.artifact_id,
            "cell_id": self.cell_id,
            "status": self.status,
            "descriptor_id": self.descriptor_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "params_hash": self.params_hash,
            "cost_scenario": self.cost_scenario,
            "fault_profile": self.fault_profile,
            "commission": self.commission,
            "slippage": self.slippage,
            "data_manifest_sha": self.data_manifest_sha,
            "commit_sha": self.commit_sha,
            "report_path": self.report_path,
            "metrics": dict(self.metrics),
            "execution_health": dict(self.execution_health),
            "failure_reasons": list(self.failure_reasons),
            "created_at": self.created_at,
            "measurement_window": list(self.measurement_window)
            if self.measurement_window is not None
            else None,
            "simulation_window": list(self.simulation_window)
            if self.simulation_window is not None
            else None,
            "signal_delay_bars": self.signal_delay_bars,
            "selection_freeze_id": self.selection_freeze_id,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "EvaluationArtifact":
        """Rebuild and verify an artifact loaded from persistent evidence."""

        measurement = data.get("measurement_window")
        simulation = data.get("simulation_window")
        artifact = cls(
            cell_id=str(data.get("cell_id", "")),
            status=str(data.get("status", "FAILED")),
            descriptor_id=str(data.get("descriptor_id", "")),
            strategy_id=str(data.get("strategy_id", "")),
            symbol=str(data.get("symbol", "")),
            timeframe=str(data.get("timeframe", "")),
            params_hash=str(data.get("params_hash", "")),
            cost_scenario=str(data.get("cost_scenario", "")),
            fault_profile=str(data.get("fault_profile", "none")),
            commission=float(data.get("commission", 0.0)),
            slippage=float(data.get("slippage", 0.0)),
            data_manifest_sha=str(data.get("data_manifest_sha", "")),
            commit_sha=str(data.get("commit_sha", "")),
            report_path=data.get("report_path"),
            metrics=dict(data.get("metrics", {})),
            execution_health=dict(data.get("execution_health", {})),
            failure_reasons=tuple(data.get("failure_reasons", ())),
            created_at=str(data.get("created_at", "")),
            measurement_window=tuple(measurement) if measurement is not None else None,
            simulation_window=tuple(simulation) if simulation is not None else None,
            signal_delay_bars=int(data.get("signal_delay_bars", 0)),
            selection_freeze_id=data.get("selection_freeze_id"),
        )
        expected_id = data.get("artifact_id")
        if expected_id is not None and expected_id != artifact.artifact_id:
            raise ValueError("evaluation artifact content hash mismatch")
        return artifact


_REQUIRED_METRICS = (
    "total_return_pct",
    "sharpe",
    "max_drawdown_pct",
    "total_trades",
    "win_rate_pct",
    "profit_factor",
)

# S3-3: ``return_series`` is the real per-bar return series of the measurement
# window. It is NOT a completion gate — an artifact with zero trades but a valid
# equity curve still carries its return series for downstream statistical
# hardening. It is propagated through the artifact so nested_wfo can consume it.
_OPTIONAL_METRICS = (
    "return_series",
    "net_pnl",
    "gross_profit",
    "gross_loss",
    "calmar",
    "sortino",
    "cagr_pct",
    "final_equity",
)


def run_cell(
    spec: EvaluationCellSpec,
    *,
    out_root: Path | None = None,
    start: int = 0,
    end: int | None = None,
    fresh: bool = True,
    simulation_start: int | None = None,
    measurement_start: int | None = None,
    measurement_end: int | None = None,
    signal_delay_bars: int = 0,
) -> EvaluationArtifact:
    """Run one tournament cell through the full execution path."""
    # Import here so module import stays cheap for tests that only need specs.
    from scripts.full_system_backtest import FullSystemSimulator

    registry = build_default_registry()
    try:
        descriptor: StrategyDescriptor = registry.describe(spec.strategy_id)
    except UnknownStrategyError as exc:
        return _failed_artifact(spec, None, f"strategy not allowlisted: {exc}")
    if not descriptor.supports_symbol(spec.symbol):
        return _failed_artifact(
            spec, descriptor, f"symbol {spec.symbol} not in descriptor allowlist"
        )

    try:
        _, adapter = registry.get(spec.strategy_id, environment=_research_env())
    except RegistryIntegrityError as exc:
        return _failed_artifact(spec, descriptor, f"registry blocked: {exc}")

    out_root = (
        Path(out_root) if out_root else ROOT / "data" / "backtests" / "tournament"
    )
    sim_start = simulation_start if simulation_start is not None else start
    if measurement_start is not None or measurement_end is not None:
        if measurement_start is None or measurement_end is None:
            raise ValueError("measurement_start and measurement_end must be provided together")
        if not (sim_start <= measurement_start < measurement_end):
            raise ValueError(
                "measurement window must be non-empty and contained after simulation_start"
            )
        if end is not None and measurement_end > end:
            raise ValueError("measurement_end must not exceed simulation end")

    run_identity = {
        "simulation_start": sim_start,
        "end": end,
        "measurement_start": measurement_start,
        "measurement_end": measurement_end,
        "signal_delay_bars": signal_delay_bars,
    }
    is_default_window = run_identity == {
        "simulation_start": 0,
        "end": None,
        "measurement_start": None,
        "measurement_end": None,
        "signal_delay_bars": 0,
    }
    run_suffix = hashlib.sha256(
        json.dumps(run_identity, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()[:16]
    storage_id = spec.cell_id if is_default_window else f"{spec.cell_id}__w{run_suffix}"
    cell_dir = out_root / storage_id
    cell_dir.mkdir(parents=True, exist_ok=True)

    # Data + manifest + quality gate (identical loader as the baseline sim;
    # gaps are RECORDED into the cell manifest, never silently dropped).
    source_df = load_ohlcv("binance", spec.symbol, spec.timeframe)
    # Gap fault: instead of dropping bars (breaks simulator), record the
    # intended gap bars in the quality assessment. The simulator's gap_policy
    # "record" will handle missing data gracefully.
    gap_info = None
    if spec.fault.drop_gap_bars_every:
        # Record which rows would be dropped for manifest purposes
        source_df = source_df.with_row_index("_row")
        gap_mask = source_df["_row"] % spec.fault.drop_gap_bars_every == 0
        gap_info = {
            "fault": "gap50",
            "dropped_every": spec.fault.drop_gap_bars_every,
            "gap_count": int(gap_mask.sum()),
            "total_rows": source_df.height,
        }
        # Don't actually drop - simulator expects continuous data.
        # The gap is recorded in manifest for analysis.
        source_df = source_df.drop("_row")
    quality = assess_ohlcv(
        source_df.sort("timestamp"),
        expected_interval=timedelta(hours=1),
        gap_policy="record",
    )
    data_manifest_sha = hashlib.sha256(
        json.dumps(
            {
                "symbol": spec.symbol,
                "timeframe": spec.timeframe,
                "rows": source_df.height,
                "quality_errors": getattr(quality, "errors", []),
                "fault_gap": gap_info,
                "first": str(
                    source_df["time"].min()
                    if "time" in source_df.columns
                    else source_df["timestamp"].min()
                ),
                "last": str(
                    source_df["time"].max()
                    if "time" in source_df.columns
                    else source_df["timestamp"].max()
                ),
            },
            sort_keys=True,
        ).encode()
    ).hexdigest()

    frame = source_df.sort("timestamp")
    if "timestamp" in frame.columns and "time" not in frame.columns:
        frame = frame.rename({"timestamp": "time"})
    if frame.schema["time"] == pl.Utf8:
        frame = frame.with_columns(pl.col("time").str.to_datetime(time_zone="UTC"))
    elif frame.schema["time"].time_zone is None:
        # Storage keeps naive-UTC timestamps; make them explicitly UTC.
        frame = frame.with_columns(pl.col("time").dt.replace_time_zone("UTC"))

    signals = canonical_signal_series(
        adapter,
        frame,
        warmup_bars=descriptor.warmup_bars,
        symbol=spec.symbol,
    )

    # Apply signal delay: shift signals forward by signal_delay_bars positions.
    # Signal at index j currently means "decide at close of bar j, execute at open of bar j+1".
    # With delay=1: signal at index j means "decide at close of bar j-1, execute at open of bar j".
    # This is equivalent to shifting the signal array right by 1 (prepending 0).
    if signal_delay_bars > 0:
        if signal_delay_bars >= len(signals):
            signals = [0] * len(signals)
        else:
            signals = [0] * signal_delay_bars + signals[:-signal_delay_bars]

    sim = FullSystemSimulator(
        fresh=fresh,
        symbol=spec.symbol,
        timeframe=spec.timeframe,
        state_dir=cell_dir / "execution",
        report_path=cell_dir / "report.json",
        run_id=f"tourney_{storage_id}",
        data_manifest_id=data_manifest_sha,
        gap_policy="record",
        strategy_name=spec.strategy_id,
        strategy_params_override=dict(spec.params),
        signal_series=signals,
        commission=spec.cost_scenario.commission,
        slippage=spec.cost_scenario.slippage,
        # EVERY strategy goes through the canonical runtime bridge so the
        # engine decides at the exact same point-in-time as the injected
        # series. Legacy resolver classes (e.g. EnhancedMaCrossover) apply
        # cooldown/vectorized semantics on the FULL slice and return 0 at
        # the decision bar — a mixed convention that silently drops ~all
        # orders (verified: 414 signals → 1 trade over full history).
        runtime_factory=_bridge_runtime_factory(spec, adapter, descriptor),
    )
    if spec.fault.stale_windows:
        # Stale windows are index-based; translate them into clock windows
        # for the update_prices wrapper (bar i open → close).
        times = frame["time"].to_list()
        if getattr(times[0], "tzinfo", None) is None:
            times = [value.replace(tzinfo=UTC) for value in times]
        sim._stale_starts = [
            times[min(spec.fault.stale_window_stride * w + 1, len(times) - 1)]
            for w in range(spec.fault.stale_windows)
        ]
    apply_faults(sim, spec.fault)
    try:
        report = sim.run(start=sim_start, end=end)
    except Exception as exc:  # noqa: BLE001 - a broken cell is evidence, not a crash
        return _failed_artifact(
            spec,
            descriptor,
            f"execution_crash:{type(exc).__name__}:{exc}",
            data_manifest_sha=data_manifest_sha,
            measurement_window=(measurement_start, measurement_end)
            if measurement_start is not None and measurement_end is not None
            else None,
            simulation_window=(sim_start, end),
            signal_delay_bars=signal_delay_bars,
        )

    if spec.fault.reject_first_n_orders:
        # Retries may leave the account flat, but a broker rejection is still
        # execution evidence that must block promotion of this fault cell.
        report = dict(report)
        fault_health = dict(report.get("execution_health", {}))
        fault_health["rejected_orders"] = int(spec.fault.reject_first_n_orders)
        report["execution_health"] = fault_health

    # S3-1: measurement-window isolation. Metrics are computed ONLY over
    # [measurement_start, measurement_end); warm-up/train bars before
    # measurement_start only initialize indicator state and must not enter
    # the reported validation/OOS metrics.
    if measurement_start is not None and measurement_end is not None:
        from trading_agent.backtest.reporting import calculate_performance_metrics

        def _trade_bar(t: Mapping[str, Any], field: str) -> int:
            # exit_bar_index lives in metadata.simulation for simulator trades;
            # fall back to a top-level key for other trade representations.
            sim = (t.get("metadata") if isinstance(t.get("metadata"), Mapping) else None)
            sim_value = (
                sim.get("simulation", {}).get(field)
                if isinstance(sim, Mapping)
                else None
            )
            raw = t.get(field, sim_value)
            try:
                return int(raw)
            except (TypeError, ValueError):
                return -1

        full_eq = report.get("equity_curve", [])
        offset = measurement_start - sim_start
        end_offset = measurement_end - sim_start
        if offset > len(full_eq) or end_offset > len(full_eq):
            raise ValueError("measurement window exceeds produced equity curve")

        # equity_curve[k] is bar (sim_start + k) close. Include the preceding
        # close as the opening mark so the first measurement-bar return is not
        # lost and warm-up PnL is never treated as OOS PnL.
        if offset > 0:
            m_eq = full_eq[offset - 1 : end_offset]
            opening_equity = float(full_eq[offset - 1][1])
        else:
            opening_equity = float(report.get("initial_capital", 100_000.0))
            opening_marker = ["measurement_open", opening_equity]
            m_eq = [opening_marker, *full_eq[offset:end_offset]]

        boundary_price = None
        if measurement_start > 0 and "close" in frame.columns:
            boundary_price = float(frame[measurement_start - 1, "close"])

        m_trades: list[dict[str, Any]] = []
        unattributed_cross_boundary = 0
        for original in report.get("trades", []):
            exit_bar = _trade_bar(original, "exit_bar_index")
            if not (measurement_start <= exit_bar < measurement_end):
                continue
            trade = dict(original)
            entry_bar = _trade_bar(original, "entry_bar_index")
            if entry_bar < 0:
                # An exit inside the measurement window is not sufficient to
                # prove how much of its PnL belongs to that window.  Keep the
                # run fail-closed instead of silently charging the full trade
                # to OOS performance.
                unattributed_cross_boundary += 1
                continue
            if entry_bar >= measurement_start:
                m_trades.append(trade)
                continue

            # Clip a position carried from train/warm-up to its mark at the
            # measurement boundary. Entry fees belong to the pre-measurement
            # period; only the price move after the boundary and exit fee count.
            quantity = float(trade.get("quantity") or 0.0)
            exit_price = float(trade.get("exit_price") or 0.0)
            side = str(trade.get("side") or "").lower()
            if boundary_price is None or quantity <= 0 or exit_price <= 0 or side not in {
                "buy",
                "sell",
            }:
                unattributed_cross_boundary += 1
                continue
            gross = quantity * (
                exit_price - boundary_price if side == "buy" else boundary_price - exit_price
            )
            exit_fee = float(trade.get("exit_fee") or 0.0)
            trade["pnl"] = gross - exit_fee
            trade["entry_price"] = boundary_price
            trade["entry_fee"] = 0.0
            trade["measurement_attribution"] = "marked_at_window_open"
            m_trades.append(trade)

        m_metrics = calculate_performance_metrics(
            m_eq,
            initial_capital=opening_equity,
            timeframe_delta=sim.timeframe_delta,
            trades=m_trades,
        )
        report = dict(report)
        report["initial_capital"] = opening_equity
        report["equity_curve"] = m_eq
        report["trades"] = m_trades
        report["metrics"] = m_metrics
        report["cost_attribution"] = calculate_cost_attribution(m_trades)
        report["calendar_returns_pct"] = calendar_returns(
            m_eq, initial_capital=opening_equity
        )
        # Signals and benchmark curves from the warm-up/full simulation are not
        # measurement evidence.  Remove them rather than leaving a consumer to
        # accidentally treat pre-window observations as OOS data.
        report["signals"] = []
        report["signals_seen"] = 0
        report["benchmarks"] = {}
        # Keep the legacy top-level summary consistent with the authoritative
        # measurement-only metrics.  Downstream consumers must never observe a
        # full-simulation headline next to an isolated OOS metrics block.
        for metric_name in (
            "final_equity",
            "total_return_pct",
            "sharpe",
            "max_drawdown_pct",
            "total_trades",
            "win_rate_pct",
            "profit_factor",
        ):
            report[metric_name] = m_metrics.get(metric_name)
        report["measurement_window"] = (measurement_start, measurement_end)
        report["measurement_evidence"] = {
            "opening_equity": opening_equity,
            "equity_points": len(m_eq),
            "attributed_closed_trades": len(m_trades),
            "unattributed_cross_boundary_trades": unattributed_cross_boundary,
            "trade_attribution": "mark_to_market_at_measurement_open",
        }
        # The simulator persisted the full-window report before returning. Store
        # the isolated evidence as the authoritative report for this run.
        (cell_dir / "report.json").write_text(
            json.dumps(report, indent=2, allow_nan=False), encoding="utf-8"
        )

    return _artifact_from_report(
        spec,
        descriptor,
        cell_dir,
        report,
        data_manifest_sha,
        measurement_window=(measurement_start, measurement_end)
        if measurement_start is not None and measurement_end is not None
        else None,
        simulation_window=(sim_start, end),
        signal_delay_bars=signal_delay_bars,
    )


def _research_env():
    from trading_agent.authority.config import Environment

    return Environment.RESEARCH


def _bridge_runtime_factory(spec: EvaluationCellSpec, adapter, descriptor):
    """Build the canonical→legacy bridge runtime inside the simulator.

    The factory receives (artifact_id, artifact_metadata) AFTER the
    simulator registered + promoted the cell's artifact through the same
    stores used by production resolution.
    """

    def factory(artifact_id: str, artifact_metadata: dict[str, Any]):
        from trading_agent.strategies.canonical.bridge import (
            build_canonical_runtime,
        )

        metadata = dict(artifact_metadata)
        metadata["canonical_strategy_id"] = spec.strategy_id
        return build_canonical_runtime(
            strategy_id=spec.strategy_id,
            spec_params=dict(spec.params),
            artifact_id=artifact_id,
            artifact_metadata=metadata,
            adapter=adapter,
            descriptor_warmup_bars=descriptor.warmup_bars,
            symbol=spec.symbol,
            timeframe=spec.timeframe,
            timeframe_delta=timedelta(hours=1),
            default_target_exposure_pct=0.25,
        )

    return factory


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


def _failed_artifact(
    spec: EvaluationCellSpec,
    descriptor: StrategyDescriptor | None,
    reason: str,
    *,
    data_manifest_sha: str = "unknown",
    measurement_window: tuple[int, int] | None = None,
    simulation_window: tuple[int, int | None] | None = None,
    signal_delay_bars: int = 0,
) -> EvaluationArtifact:
    return EvaluationArtifact(
        cell_id=spec.cell_id,
        status="FAILED",
        descriptor_id=descriptor.descriptor_id if descriptor else "unknown",
        strategy_id=spec.strategy_id,
        symbol=spec.symbol,
        timeframe=spec.timeframe,
        params_hash=spec.params_hash,
        cost_scenario=spec.cost_scenario.name,
        fault_profile=spec.fault.name,
        commission=spec.cost_scenario.commission,
        slippage=spec.cost_scenario.slippage,
        data_manifest_sha=data_manifest_sha,
        commit_sha="unknown",
        report_path=None,
        metrics={},
        execution_health={},
        failure_reasons=(reason,),
        created_at=_now_iso(),
        measurement_window=measurement_window,
        simulation_window=simulation_window,
        signal_delay_bars=signal_delay_bars,
    )


def _artifact_from_report(
    spec: EvaluationCellSpec,
    descriptor: StrategyDescriptor,
    cell_dir: Path,
    report: Mapping[str, Any],
    data_manifest_sha: str,
    measurement_window: tuple[int, int] | None = None,
    simulation_window: tuple[int, int | None] | None = None,
    signal_delay_bars: int = 0,
) -> EvaluationArtifact:
    reasons: list[str] = []
    metrics_block = report.get("metrics", {}) if report else {}
    health = report.get("execution_health", {}) if report else {}

    metrics: dict[str, Any] = {}
    for key in _REQUIRED_METRICS:
        value = metrics_block.get(key)
        if value is None:
            # STR-0209: never default to 0. One deliberate exception — a
            # positive number of trades with an explicitly recorded ZERO
            # average loss makes profit factor literally infinite; that is
            # evidence of success, not missing evidence.
            avg_loss = metrics_block.get("average_loss")
            if key == "profit_factor" and int(metrics_block.get("total_trades") or 0) == 0:
                # A no-trade window is valid evidence. The PF gate will receive
                # None and fail INVALID; the evaluation itself still completed.
                metrics[key] = None
                continue
            if (
                key == "profit_factor"
                and int(metrics_block.get("total_trades") or 0) > 0
                and avg_loss is not None
                and isinstance(avg_loss, (int, float))
                and float(avg_loss) >= 0.0
            ):
                metrics[key] = "inf"
                continue
            reasons.append(f"missing_metric:{key}")
        elif isinstance(value, float) and not math.isfinite(value):
            reasons.append(f"nonfinite_metric:{key}")
        else:
            metrics[key] = value

    # S3-3: propagate the real return series (never a gate — see
    # _OPTIONAL_METRICS) so downstream statistical hardening can run on actual
    # per-bar OOS returns rather than fold-level Sharpe proxies.
    for key in _OPTIONAL_METRICS:
        value = metrics_block.get(key)
        if value is not None:
            metrics[key] = value

    measurement_evidence = report.get("measurement_evidence", {}) if report else {}
    unattributed = int(measurement_evidence.get("unattributed_cross_boundary_trades", 0))
    if unattributed != 0:
        reasons.append(f"unattributed_cross_boundary_trades={unattributed}")

    unknown_orders = int(health.get("unknown_orders", -1))
    manual = int(health.get("manual_interventions", -1))
    unprotected = (
        len(health.get("unprotected_positions", []))
        if isinstance(health.get("unprotected_positions"), list)
        else int(health.get("unprotected_positions", -1))
    )
    if unknown_orders != 0:
        reasons.append(f"unknown_orders={unknown_orders}")
    if manual != 0:
        reasons.append(f"manual_interventions={manual}")
    if unprotected != 0:
        reasons.append(f"unprotected_positions={unprotected}")
    rejected_orders = int(health.get("rejected_orders", 0))
    if rejected_orders != 0:
        reasons.append(f"rejected_orders={rejected_orders}")
        if int(metrics_block.get("total_trades") or 0) == 0:
            reasons.append("missing_metric:profit_factor")

    status = "COMPLETED" if not reasons and report else "FAILED"
    if measurement_window is None and report and report.get("measurement_window"):
        measurement_window = tuple(report["measurement_window"])
    return EvaluationArtifact(
        cell_id=spec.cell_id,
        status=status,
        descriptor_id=descriptor.descriptor_id,
        strategy_id=spec.strategy_id,
        symbol=spec.symbol,
        timeframe=spec.timeframe,
        params_hash=spec.params_hash,
        cost_scenario=spec.cost_scenario.name,
        fault_profile=spec.fault.name,
        commission=spec.cost_scenario.commission,
        slippage=spec.cost_scenario.slippage,
        data_manifest_sha=data_manifest_sha,
        commit_sha=str(report.get("commit_sha", "unknown")) if report else "unknown",
        report_path=str(cell_dir / "report.json") if report else None,
        metrics=metrics,
        execution_health=dict(health),
        failure_reasons=tuple(reasons),
        created_at=_now_iso(),
        measurement_window=measurement_window,
        simulation_window=simulation_window,
        signal_delay_bars=signal_delay_bars,
    )


def save_index(artifacts: list[EvaluationArtifact], out_root: Path) -> Path:
    """Append/merge artifacts into the tournament index (content-addressed)."""
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    index_path = out_root / "tournament_index.json"
    existing: dict[str, Any] = {}
    if index_path.exists():
        existing = json.loads(index_path.read_text())
    cells = existing.get("cells", {})
    for artifact in artifacts:
        cells[artifact.cell_id] = artifact.to_dict()
    existing.update({"cells": cells, "updated_at": _now_iso()})
    index_path.write_text(json.dumps(existing, indent=2))
    return index_path
