#!/usr/bin/env python3
"""Generate docs/PROJECT_MAP.md from the git-tracked repository tree.

Usage:
    python scripts/generate_project_map.py [--check]

--check exits non-zero if the generated file differs from the committed one
(used by CI to detect stale generated docs).

The map is built from `git ls-files` (tracked files only) so that ignored
build/runtime artifacts (egg-info, node_modules, dist, credentials, .env,
agent workspace files, ...) can never make it stale — CI checkout and the
author's working tree always produce the same listing.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "docs" / "PROJECT_MAP.md"

# Extra pruning on top of "tracked files only": directories/files that are
# runtime data or generated and should never appear in the project map.
EXCLUDED_DIRS = {
    "data",
    "logs",
    "media",
    "backup",
    "backups",
    "node_modules",
}
EXCLUDED_FILES = {"poetry.lock", "package-lock.json", "tsconfig.tsbuildinfo"}


def tracked_files(root: Path) -> list[str]:
    """Return git-tracked file paths (relative to root), sorted."""
    out = subprocess.check_output(
        ["git", "-C", str(root), "ls-files", "-z"], text=False
    )
    files = [f.decode("utf-8", "replace") for f in out.split(b"\0") if f]
    # Respect worktree deletions while they are still unstaged. This keeps the
    # generated map useful during a cleanup branch instead of listing files
    # that no longer exist on disk but remain in the index until commit.
    return sorted(f for f in files if (root / f).exists())


def render_tree(files: list[str]) -> list[str]:
    """Render a nested directory tree from sorted file paths."""
    # Build nested dict: {"dir": {"sub": {}}, "file": None}
    root: dict = {}
    for path in files:
        parts = path.split("/")
        node = root
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None

    lines: list[str] = []

    def prune(node: dict) -> dict:
        """Drop excluded entries from the tree."""
        return {
            k: (prune(v) if isinstance(v, dict) else None)
            for k, v in node.items()
            if k not in EXCLUDED_DIRS and k not in EXCLUDED_FILES
        }

    def walk(node: dict, prefix: str) -> None:
        entries = sorted(node.items(), key=lambda kv: (kv[1] is None, kv[0]))
        for i, (name, child) in enumerate(entries):
            last = i == len(entries) - 1
            connector = "└── " if last else "├── "
            lines.append(f"{prefix}{connector}{name}")
            if isinstance(child, dict):
                walk(child, prefix + ("    " if last else "│   "))

    walk(prune(root), "")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if output is stale"
    )
    args = parser.parse_args()

    files = tracked_files(REPO_ROOT)
    header = [
        "# Project Map (generated)",
        "",
        "> ⚠️ AUTO-GENERATED by `scripts/generate_project_map.py` — đừng sửa tay.",
        "> Chạy lại script khi cây thư mục thay đổi; CI kiểm tra file này không stale.",
        "> Chỉ liệt kê git-tracked files (bỏ qua artifact/credentials/env).",
        "",
        "```",
    ]
    footer = ["```", ""]
    content = "\n".join(header + render_tree(files) + footer) + "\n"

    old = OUTPUT.read_text() if OUTPUT.exists() else None
    if args.check:
        if old != content:
            print(
                f"ERROR: {OUTPUT.relative_to(REPO_ROOT)} is stale — run "
                "`python scripts/generate_project_map.py` and commit the change."
            )
            return 1
        print(f"OK: {OUTPUT.relative_to(REPO_ROOT)} is up to date.")
        return 0

    OUTPUT.write_text(content)
    print(
        f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(files)} files, "
        f"{len(render_tree(files))} visible entries)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
