#!/usr/bin/env python3
"""Generate docs/PROJECT_MAP.md from the live repository tree.

Usage:
    python scripts/generate_project_map.py [--check]

--check exits non-zero if the generated file differs from the committed one
(used by CI to detect stale generated docs).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "docs" / "PROJECT_MAP.md"

# Directories/files that are runtime artifacts or third-party — never shown.
EXCLUDED_DIRS = {
    ".git", "node_modules", "__pycache__", ".pytest_cache", ".mypy_cache",
    ".ruff_cache", "venv", ".venv", "data", "logs", "media", "memory",
    "build", "dist", ".eggs", "trading_agent.egg-info",
    ".agents", ".webui", "strategies_repo", "backup", "backups",
    # QwenPaw agent workspace runtime (gitignored)
    "browser", "sessions", "missions", "embedding_cache", "dialog",
    "tool_result", "tool_results", "skills", "digest", "refs", "drivers",
    "active_skills", "customized_skills", "ralph_loops",
}
EXCLUDED_FILES = {".coverage", "poetry.lock", "package-lock.json",
                  "tsconfig.tsbuildinfo"}


def tree_lines(root: Path, prefix: str = "") -> list[str]:
    lines: list[str] = []
    entries = sorted(
        (p for p in root.iterdir() if p.name not in EXCLUDED_DIRS
         and p.name not in EXCLUDED_FILES and not p.name.startswith(".")),
        key=lambda p: (p.is_file(), p.name),
    )
    for i, p in enumerate(entries):
        last = i == len(entries) - 1
        connector = "└── " if last else "├── "
        lines.append(f"{prefix}{connector}{p.name}")
        if p.is_dir():
            lines.extend(tree_lines(p, prefix + ("    " if last else "│   ")))
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit non-zero if output is stale")
    args = parser.parse_args()

    top = REPO_ROOT
    header = [
        "# Project Map (generated)",
        "",
        "> ⚠️ AUTO-GENERATED by `scripts/generate_project_map.py` — đừng sửa tay.",
        "> Chạy lại script khi cây thư mục thay đổi; CI kiểm tra file này không stale.",
        "",
        "```",
    ]
    body = tree_lines(top)
    footer = ["```", ""]
    content = "\n".join(header + body + footer) + "\n"

    old = OUTPUT.read_text() if OUTPUT.exists() else None
    if args.check:
        if old != content:
            print(f"ERROR: {OUTPUT.relative_to(REPO_ROOT)} is stale — run "
                  "`python scripts/generate_project_map.py` and commit the change.")
            return 1
        print(f"OK: {OUTPUT.relative_to(REPO_ROOT)} is up to date.")
        return 0

    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(body)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
