"""Event-sourced execution lifecycle (Wave C — Execution State & Resilience)."""

from trading_agent.execution.lifecycle.events import (
    EVENT_SCHEMA_VERSION,
    EventValidationError,
    ExecutionEvent,
    ExecutionEventType,
    make_event,
    validate_event,
)
from trading_agent.execution.lifecycle.lifecycle import (
    LIVE_STATUSES,
    ExecutionHealth,
    ExecutionLifecycle,
    ExposureEffect,
    IntentStatus,
    InvariantViolation,
    LifecycleError,
    LifecycleState,
    OrderState,
    PortfolioRiskSnapshot,
    ProtectionState,
    ProtectiveOrderState,
    ReconciliationState,
    TrustedPrice,
)
from trading_agent.execution.lifecycle.store import (
    CUTOVER_MIGRATION_VERSION,
    CutoverMetadata,
    ExecutionEventStore,
    LegacyCutoverStateRequired,
    LegacyMigrationError,
    ReservationConflictError,
    SequenceGapError,
    Snapshot,
    SnapshotIntegrityError,
    snapshot_checksum,
)

__all__ = [
    "EVENT_SCHEMA_VERSION",
    "EventValidationError",
    "ExecutionEvent",
    "ExecutionEventType",
    "ExecutionEventStore",
    "ExecutionLifecycle",
    "ExposureEffect",
    "ExecutionHealth",
    "IntentStatus",
    "InvariantViolation",
    "LifecycleError",
    "LegacyCutoverStateRequired",
    "LegacyMigrationError",
    "LifecycleState",
    "LIVE_STATUSES",
    "OrderState",
    "PortfolioRiskSnapshot",
    "ProtectiveOrderState",
    "ProtectionState",
    "ReconciliationState",
    "ReservationConflictError",
    "SequenceGapError",
    "Snapshot",
    "SnapshotIntegrityError",
    "CutoverMetadata",
    "CUTOVER_MIGRATION_VERSION",
    "TrustedPrice",
    "make_event",
    "snapshot_checksum",
    "validate_event",
]
