"""Research governance package (Wave B).

Immutable strategy artifacts, promotion state machine, uncertainty gate,
abstention codes, drift/health detection and multiple-testing governance.
"""

from trading_agent.research.artifact import (
    ArtifactStore,
    PersistentArtifactStore,
    StrategyArtifact,
    build_strategy_artifact,
    canonical_params,
    data_manifest_hash,
    hash_file,
    sha256_hex,
)
from trading_agent.research.drift import (
    DriftLevel,
    DriftMonitor,
    DriftResult,
    StrategyHealthState,
    psi,
)
from trading_agent.research.lifecycle import (
    ArtifactLifecycle,
    PromotionError,
    PromotionEvent,
    PromotionEvidence,
    PromotionPolicy,
    PromotionState,
    calibration_evidence,
    drift_check_evidence,
    manual_review_evidence,
    reality_gap_evidence,
    soak_test_evidence,
)
from trading_agent.research.trials import (
    TrialRecord,
    TrialsRegistry,
    param_hash,
    search_space_hash,
)
from trading_agent.research.uncertainty import (
    ABSTENTION_CODES,
    Abstention,
    AbstentionReason,
    Action,
    CalibratedDecision,
    DecisionPolicy,
    ThresholdDecisionPolicy,
    UncertaintySignal,
    UncertaintyState,
    isotonic_calibration,
    should_abstain,
    temperature_scale,
    uncertainty_gate,
    uncertainty_signal_to_decision,
)

__all__ = [
    "ABSTENTION_CODES",
    "Abstention",
    "AbstentionReason",
    "Action",
    "ArtifactLifecycle",
    "ArtifactStore",
    "CalibratedDecision",
    "DecisionPolicy",
    "DriftLevel",
    "DriftMonitor",
    "DriftResult",
    "PersistentArtifactStore",
    "PromotionError",
    "PromotionEvent",
    "PromotionEvidence",
    "PromotionPolicy",
    "PromotionState",
    "StrategyArtifact",
    "StrategyHealthState",
    "ThresholdDecisionPolicy",
    "TrialRecord",
    "TrialsRegistry",
    "UncertaintySignal",
    "UncertaintyState",
    "build_strategy_artifact",
    "calibration_evidence",
    "canonical_params",
    "data_manifest_hash",
    "drift_check_evidence",
    "hash_file",
    "isotonic_calibration",
    "manual_review_evidence",
    "param_hash",
    "psi",
    "reality_gap_evidence",
    "search_space_hash",
    "sha256_hex",
    "should_abstain",
    "soak_test_evidence",
    "temperature_scale",
    "uncertainty_gate",
    "uncertainty_signal_to_decision",
]
